#!/bin/sh

java -version

echo "Unzipping sdk tools"
sed -i 's/r12b/r20b/g' setup.sh && sed -i '41,48d' setup.sh && chmod +x setup.sh
 ./setup.sh

echo "sdk installed in $ANDROID_HOME"
echo "ndk installed in $ANDROID_NDK_HOME"
